### ISSUE TITLE
Set Up Video Camera Embedding and Facial Detection Model for Google Classroom

### ISSUE THREAD

**Issue by Yuliy97** [JKChenFZ/Minerva#24]
- only add the embedding after user clicked on the Youtube link
- the camera embedding should detect face

**Comment by Jason-KChen** [comment]
Good practices to keep in mind:
1. Keep your pull request/commits small, anything over 100+ lines in a pull request incurs unnecessary overheads on the reviewer
2. While working on the same issue, it is okay to have multiple branches. E.g. If you have 4 different sub-tasks, have each sub-task in its own branch. The second task should be based(branches off) on the first task. As with pull requests, open and close then sequentially.
3. In the commit message, prefix the message with `[#issueNumber]` like `[#1]` for easy referencing. You don't have to do that for small commits like fixing a line
4. Once a pull request is opened, check the linter and the code you submitted (under `changed files` tab) to make sure everything is correct
5. After revision, please re-request review by clicking on the circle next to reviewer names
6. If the change has to do with UI, please include screenshots of the changed UI as part of the pull request
7. If your feature branch is stale, always `rebase` instead of `merge`. Also try to avoid `force pushes`

**Comment by Jason-KChen** [comment]
Let's break this down into different milestone,
1. integrate a real-time video feed into the video player overlay
2. activate facial detection of the video feed
3. feed image data into the model
